---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: 2.3.7
serverless_language: ''
polling_url: https://www.wienerlinien.at/ogd_realtime/monitor?stopId={{wl_station}}
polling_headers: ''
polling_body: ''
id: 98534
custom_fields:
- keyname: author_info
  name: About This Plugin
  description: Metro departures for Vienna, Austria. Data attribution data.gv.at
  category: travel
  field_type: author_bio
  github_url: https://github.com/bnussbau/trmnl-vienna-metro-departures
  email_address: trmnl@benjaminnussbaum.at
- keyname: wl_station
  field_type: number
  name: WL StopId
  description: Stop ID
  placeholder: 4111
  help_text: Get your Stop ID here <a href="https://till.mabe.at/rbl" target="_blank" class="underline">https://till.mabe.at/rbl</a>
name: Vienna Metro Departures (Wiener Linien)
refresh_interval: 15
